sudo: required
services:
  - docker

script:
  - docker build -t "$DOCKER_USERNAME/$DOCKER_REPONAME" ./debian
  - docker images
  - docker login -u "$DOCKER_USERNAME" --password-stdin <<< "$DOCKER_PASSWORD"
  - docker push "$DOCKER_USERNAME/$DOCKER_REPONAME"
